//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FriendLink
    {
        public int requester { get; set; }
        public int requested { get; set; }
        public bool best_friend { get; set; }
        public System.DateTime timestamp { get; set; }
        public bool read { get; set; }
        public bool approved { get; set; }
    
        public virtual Profile Requester_Profile { get; set; }
        public virtual Profile Requested_Profile { get; set; }
    }
}
